name:               Catalyst-Plugin-Params-Demoronize
version:            1.12
abstract:           convert non-ISO extended ASCII characters into sane alternatives
license:            perl
version_from:       lib/Catalyst/Plugin/Params/Demoronize.pm
installdirs:        site
distribution_type:  module
generated_by:       Mike Eldridge <diz@cpan.org>
author:
  - Mike Eldridge <diz@cpan.org>
